-- MySQL Script generated by MySQL Workbench
-- Sat Apr 25 23:55:36 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ecommerce
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ecommerce` ;

-- -----------------------------------------------------
-- Schema ecommerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecommerce` DEFAULT CHARACTER SET utf8mb4 ;
USE `ecommerce` ;

-- -----------------------------------------------------
-- Table `ecommerce`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único do cliente.',
  `Nome` VARCHAR(100) NOT NULL COMMENT 'Nome completo do cliente.',
  `CPF` CHAR(11) NOT NULL COMMENT 'Cadastro de Pessoa Física do cliente. Deve ser único.',
  `Endereco` VARCHAR(150) NULL COMMENT 'Endereço principal do cliente.\n',
  `DataNascimento` DATE NOT NULL COMMENT 'Data de nascimento do cliente.',
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `cpf_unique` (`CPF` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`Pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`Pedido` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`Pedido` (
  `idPedido` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único do pedido. Chave primária da tabela Pedido.',
  `Pedido_idCliente` INT NOT NULL COMMENT 'Referência ao cliente que realizou o pedido. Chave estrangeira para Cliente.idCliente.',
  `StatusPedido` ENUM('Pendente', 'Processando', 'Enviado', 'Entregue', 'Cancelado') NOT NULL DEFAULT 'Pendente' COMMENT 'Status atual do pedido no processo de compra (ex: \'Pendente\',\'Processando\',\'Enviado\',\'Entregue\',\'Cancelado\').',
  `Descricao` VARCHAR(255) NULL COMMENT 'Descrição adicional do pedido, podendo conter observações ou detalhes relevantes.',
  `Frete` DECIMAL(10,2) NULL COMMENT 'Valor do frete cobrado para a entrega do pedido.',
  `DataPedido` DATETIME NOT NULL COMMENT 'Data e hora em que o pedido foi realizado.',
  PRIMARY KEY (`idPedido`),
  INDEX `fk_pedido_cliente_idx` (`Pedido_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_cliente`
    FOREIGN KEY (`Pedido_idCliente`)
    REFERENCES `ecommerce`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`Produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`Produto` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`Produto` (
  `idProduto` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único do produto.',
  `Nome` VARCHAR(100) NOT NULL COMMENT 'Nome comercial do produto.\n',
  `Categoria` ENUM('Eletronico', 'Vestimenta', 'Brinquedos', 'Alimentos', 'Moveis') NOT NULL COMMENT 'Categoria comercial do produto.',
  `Avaliacao` DECIMAL(3,2) NULL DEFAULT 0 COMMENT 'Média de avaliação do produto baseada em feedback dos clientes.',
  `Dimensao` VARCHAR(45) NOT NULL COMMENT 'Dimensões físicas do produto, como altura, largura e profundidade.',
  `Preco` DECIMAL(10,2) NOT NULL COMMENT 'Preço unitário atual do produto.',
  PRIMARY KEY (`idProduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`Fornecedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`Fornecedor` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`Fornecedor` (
  `idFornecedor` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único do fornecedor.\n',
  `RazaoSocial` VARCHAR(100) NOT NULL COMMENT 'Nome jurídico do fornecedor.',
  `CNPJ` CHAR(14) NOT NULL COMMENT 'Cadastro Nacional da Pessoa Jurídica do fornecedor. Deve ser único para cada fornecedor.',
  `Contato` VARCHAR(100) NULL COMMENT 'Informação de contato do fornecedor.',
  PRIMARY KEY (`idFornecedor`),
  UNIQUE INDEX `CNPJ_UNIQUE` (`CNPJ` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`Produto_Fornecedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`Produto_Fornecedor` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`Produto_Fornecedor` (
  `Fornecedor_idFornecedor` INT NOT NULL COMMENT 'Referência ao fornecedor do produto. Chave estrangeira para Fornecedor.idFornecedor.\n',
  `Produto_idProduto` INT NOT NULL COMMENT 'Referência ao produto fornecido. Chave estrangeira para Produto.idProduto.',
  `QuantidadePadrao` INT NOT NULL DEFAULT 1 COMMENT 'Quantidade padrão fornecida do produto pelo fornecedor. Valor default é 1 quando não especificado.',
  PRIMARY KEY (`Fornecedor_idFornecedor`, `Produto_idProduto`),
  INDEX `fk_produto_fornecedor_produto_idx` (`Produto_idProduto` ASC) VISIBLE,
  INDEX `fk_produto_fornecedor_fornecedor_idx` (`Fornecedor_idFornecedor` ASC) VISIBLE,
  CONSTRAINT `fk_produto_fornecedor_fornecedor`
    FOREIGN KEY (`Fornecedor_idFornecedor`)
    REFERENCES `ecommerce`.`Fornecedor` (`idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_fornecedor_produto`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `ecommerce`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`Estoque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`Estoque` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`Estoque` (
  `idEstoque` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único do estoque ou centro de distribuição.\n',
  `Localizacao` VARCHAR(100) NOT NULL COMMENT 'Localização física onde os produtos são armazenados.',
  PRIMARY KEY (`idEstoque`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`Produto_Estoque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`Produto_Estoque` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`Produto_Estoque` (
  `Produto_idProduto` INT NOT NULL COMMENT 'Referência ao produto armazenado. Chave estrangeira para Produto.idProduto.',
  `Estoque_idEstoque` INT NOT NULL COMMENT 'Referência ao estoque onde o produto está armazenado. Chave estrangeira para Estoque.idEstoque.',
  `Quantidade` INT NOT NULL COMMENT 'Quantidade disponível do produto em um determinado estoque.',
  PRIMARY KEY (`Produto_idProduto`, `Estoque_idEstoque`),
  INDEX `fk_produto_estoque_estoque_idx` (`Estoque_idEstoque` ASC) VISIBLE,
  INDEX `fk_produto_estoque_produto_idx` (`Produto_idProduto` ASC) VISIBLE,
  CONSTRAINT `fk_produto_estoque_produto`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `ecommerce`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_estoque_estoque`
    FOREIGN KEY (`Estoque_idEstoque`)
    REFERENCES `ecommerce`.`Estoque` (`idEstoque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`Pedido_Produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`Pedido_Produto` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`Pedido_Produto` (
  `Produto_idProduto` INT NOT NULL COMMENT 'Referência ao produto incluído no pedido. Chave estrangeira para Produto.idProduto.',
  `Pedido_idPedido` INT NOT NULL COMMENT 'Referência ao pedido que contém o produto. Chave estrangeira para Pedido.idPedido.',
  `Quantidade` INT NOT NULL DEFAULT 1 COMMENT 'Quantidade do produto incluída no pedido.\n',
  `PrecoUnitario` DECIMAL(10,2) NOT NULL COMMENT 'Preço unitário do produto no momento da compra.',
  PRIMARY KEY (`Produto_idProduto`, `Pedido_idPedido`),
  INDEX `fk_pedido_produto_pedido_idx` (`Pedido_idPedido` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_produto_pedido`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `ecommerce`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_produto_produto`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `ecommerce`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`Vendedor_Terceiro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`Vendedor_Terceiro` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`Vendedor_Terceiro` (
  `idTerceiro` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único do vendedor terceiro no marketplace.',
  `RazaoSocial` VARCHAR(100) NULL COMMENT 'Nome jurídico do vendedor terceiro.',
  `Localizacao` VARCHAR(100) NULL COMMENT 'Localização do vendedor terceiro.',
  `NomeFantasia` VARCHAR(100) NULL COMMENT 'Nome comercial utilizado pelo vendedor terceiro.\n',
  `CNPJ` CHAR(14) NULL COMMENT 'Cadastro Nacional da Pessoa Jurídica do vendedor terceiro, quando aplicável.',
  `CPF` CHAR(11) NULL COMMENT 'Cadastro de Pessoa Física do vendedor terceiro, quando aplicável.',
  PRIMARY KEY (`idTerceiro`),
  UNIQUE INDEX `CNPJ_UNIQUE` (`CNPJ` ASC) VISIBLE,
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`Produto_Terceiro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`Produto_Terceiro` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`Produto_Terceiro` (
  `Vendedor_idTerceiro` INT NOT NULL COMMENT 'Referência ao vendedor terceiro que comercializa o produto. Chave estrangeira para Vendedor_Terceiro.idTerceiro.',
  `Produto_idProduto` INT NOT NULL COMMENT 'Referência ao produto vendido por terceiros. Chave estrangeira para Produto.idProduto.',
  `Quantidade` INT NOT NULL DEFAULT 1 COMMENT 'Quantidade disponível do produto com o vendedor terceiro.',
  PRIMARY KEY (`Vendedor_idTerceiro`, `Produto_idProduto`),
  INDEX `fk_produto_terceiro_produto_idx` (`Produto_idProduto` ASC) VISIBLE,
  CONSTRAINT `fk_produto_terceiro_vendedor`
    FOREIGN KEY (`Vendedor_idTerceiro`)
    REFERENCES `ecommerce`.`Vendedor_Terceiro` (`idTerceiro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_terceiro_produto`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `ecommerce`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`Pagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`Pagamento` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`Pagamento` (
  `idPagamento` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único do pagamento. Chave primária da tabela Pagamento.',
  `Valor` DECIMAL(10,2) NOT NULL COMMENT 'Valor pago referente ao pedido.',
  `TipoPagamento` ENUM('Boleto', 'Pix', 'Cartao') NOT NULL COMMENT 'Forma de pagamento utilizada (ex: cartão, boleto, PIX).',
  `Pagamento_idPedido` INT NOT NULL COMMENT 'Referência ao pedido associado ao pagamento. Chave estrangeira para Pedido.idPedido.',
  `DataPagamento` DATETIME NULL COMMENT 'Data e hora em que o pagamento foi realizado.',
  PRIMARY KEY (`idPagamento`),
  INDEX `fk_pagamento_pedido_idx` (`Pagamento_idPedido` ASC) VISIBLE,
  CONSTRAINT `fk_pagamento_pedido`
    FOREIGN KEY (`Pagamento_idPedido`)
    REFERENCES `ecommerce`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
